Algoritmo "Exercicio3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : José Erinaldo da Fonseca
// Descrição   : 3) Crie um algoritmo que lê o valor do raio e calcule a área do círculo correspondente.
// Autor(a)    : Helder Kennedy Campos
// Data atual  : 01/02/2023
Var
raio, areaCirc: real



Inicio
escreva("Informe o valor do raio para calcular a àrea do circulo: ")
leia(raio)
areaCirc <- 3.14*raio^2
escreva("A área do circulo é: ", areaCirc)
Fimalgoritmo